//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ALPOGalleryTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://alpo-astronomy.org/gallery3/index.php/Venus_Images_and_Observations/Venus-" +
            "2023-2024/")]
        public string VenusUrl {
            get {
                return ((string)(this["VenusUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://alpo-astronomy.org/gallery3/index.php/Solar-Observations-Archive/")]
        public string SolarUrl {
            get {
                return ((string)(this["SolarUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://alpo-astronomy.org/gallery3/index.php/Saturn-Images-and-Observations/Satur" +
            "n-Images-YYYY/")]
        public string SaturnUrl {
            get {
                return ((string)(this["SaturnUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://alpo-astronomy.org/gallery3/index.php/Remote-Planets-Images/2020-2021/")]
        public string RemoteUrl {
            get {
                return ((string)(this["RemoteUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("mongodb+srv://alpoReader:30Jrq2Rq2V6eDDIK@tomneytrain0-zgh3l.mongodb.net/test?ret" +
            "ryWrites=true&w=majority")]
        public string MongoCnnStr {
            get {
                return ((string)(this["MongoCnnStr"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://alpo-astronomy.org/gallery3/index.php/Mars-Images-and-Observations/2022-Ma" +
            "rs-Apparition/")]
        public string MarsUrl {
            get {
                return ((string)(this["MarsUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://alpo-astronomy.org/gallery3/index.php/Jupiter-Images-and-Observations/Appa" +
            "rition-2022/")]
        public string JupiterUrl {
            get {
                return ((string)(this["JupiterUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jim\\OneDrive\\Documents\\Astronomy\\ALPO Online Content\\Solar\\Reports")]
        public string SolarStaged {
            get {
                return ((string)(this["SolarStaged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jim\\OneDrive\\Documents\\Astronomy\\ALPO Online Content\\Jupiter\\Reports")]
        public string JupiterStaged {
            get {
                return ((string)(this["JupiterStaged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jim\\OneDrive\\Documents\\Astronomy\\ALPO Online Content\\Mars\\Reports")]
        public string MarsStaged {
            get {
                return ((string)(this["MarsStaged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jim\\OneDrive\\Documents\\Astronomy\\ALPO Online Content\\Saturn\\Reports")]
        public string SaturnStaged {
            get {
                return ((string)(this["SaturnStaged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jim\\OneDrive\\Documents\\Astronomy\\ALPO Online Content\\Venus\\Reports")]
        public string VenusStaged {
            get {
                return ((string)(this["VenusStaged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jim\\OneDrive\\Documents\\Astronomy\\ALPO Online Content\\Mercury\\Reports")]
        public string MercuryStaged {
            get {
                return ((string)(this["MercuryStaged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jim\\OneDrive\\Documents\\Astronomy\\ALPO Online Content\\Remote_Planets\\Repo" +
            "rts")]
        public string RemoteStaged {
            get {
                return ((string)(this["RemoteStaged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Users\\Jim\\OneDrive\\Documents\\Astronomy\\ALPO Online Content\\Eclipse\\Reports")]
        public string EclipseStaged {
            get {
                return ((string)(this["EclipseStaged"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://alpo-astronomy.org/gallery3/index.php/Eclipse-Images/")]
        public string EclipseUrl {
            get {
                return ((string)(this["EclipseUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://alpo-astronomy.org/gallery3/index.php/MercuryImagesandObservations/Mercury" +
            "_2023/")]
        public string MercuryUrl {
            get {
                return ((string)(this["MercuryUrl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:s25.winhost.com;Initial Catalog=DB_50230_familydata;Persist Secur" +
            "ity Info=True;User ID=DB_50230_familydata_user;Password=P!sc3sGlyxM74")]
        public string SqlSrvCnnStr {
            get {
                return ((string)(this["SqlSrvCnnStr"]));
            }
        }
    }
}
